### PR TITLE
Added all the test to 90!!

### PR DESCRIPTION
**Pull request by junxjr**
**Title**
Added all the test to 90!!

**Issue Number**
Fixes Issue #58

**Description**
This PR improves the authentication API endpoint by addressing issues and adding robust testing.

**Changes:**
Initialized variables and mock objects for proper testing environment setup.
Mocked Mongoboi class for controlled testing of database interactions.
Added four test cases covering various authentication scenarios.
Improved error handling for database operation errors.
Enhanced test assertions for verifying status code and response body.
These changes enhance the reliability and functionality of the authentication API endpoint.

**Testing**
Coverage 100% and global coverage reached 90%

**IMPORTANT NOTE**
These tests are completed by Johnson.

**Possible Errors**
There is no errors.

**Image**
image

### CODE REVIEW

**Review by tbg510 — APPROVED** [review]
Nice tests !!! I LOVE THE NUMBER 90 WOOOOOOOOOOOOOOOOOOOO !!!

**Review by aiharc1 — APPROVED** [review]
HORRAY WE DID IT. Nice work brining us to 90%

**Review by jusasin — APPROVED** [review]
I see that we are able to change the global checks back to 90 to make sure to add coverage. It is great to see that we have gotten up to 90.

**Review by salazw1 — APPROVED** [review]
Excellent work! Thanks to this pull request, we are now at the 90%+ requirement for test coverage!

**Pull request merged**
