### PR TITLE
Move food page under pages router and move food component under new layout

### LINKED ISSUE #195: Move Food page under new pages  router and layout component
### Description
Now that we've begun utilizing the pages directory to put all pages under, the Food page needs to be placed under its own directory in pages. In addition to this, the existing layout overhaul needs to be placed on top of the Food page.

### Expected Behavior
Navigating to the /food page on our vercel deployment should show the existing Food items but under the new page layout.

### PR DESCRIPTION
**Pull request by blake-gilmore**
## Description
This PR simply moves the existing food file under the pages/food directory, and moves the test file under the __tests__ directory. The new layout component is also placed on top of the food page. 

## Testing
I verified that the existing test for the food page still passes.

### CODE REVIEW

**Review by AlvaroH2001 — APPROVED** [review]
Great job on this, took a load off everyone's shoulders including my own by converting this to the new layout. Great job on the conversion to the index file structure.

**Review by tbg510 — APPROVED** [review]
Nice work on converting the Food page to the new layout. It's important that we keep all of our pages consistent with the same layouts.

**Review by nguyenj21 — APPROVED** [review]
Remember to document AI if you have not done so already. Good job, new layout is looking spiffy like you

**Review by jusasin — APPROVED** [review]
Good additions to change where the files are located so that they are located correctly. Good job! Very good!

**Pull request merged**
