### PR TITLE
added test cases for registerToDB and updated registerToDB 

### PR DESCRIPTION
**Pull request by nguyenj21**
Issue Number: #76 

Description: Updated registerToDB to have module.exports in order for my test cases for registerToDB to work. added my test cases

Testing: registerToDB 
should create a new user 
should return null if there is an error 
should always disconnect from the database 
should return null if there is an error while hashing the password 

Possible Errors: Working on username.js to be 100% but I don't think it is possible, 90% should be the highest due to testing with the database

Image:
image
image

### CODE REVIEW

**Review by salazw1 — APPROVED** [review]
Great work on adding more to our overall test coverage! I ran the test locally and it does seem registerToDB.js now has 100% coverage even after the recent changes to the file.
image
image




A minor note: I do see when running in to the console.error line, it outputs to the terminal  an issue, but I believe this should be the case in order to show that the testing for salting/hashing a password in the fail case is successful.
image

**Review by junxjr — APPROVED** [review]
Great implementation on test cases. When I ran the test files, the coverage for register file %branch was 100%. I see the test coverages are getting completed for most of the security part, great progress! I also notice the warnings for console errors, but it seems like a lot of the test files has it for testing purposes.

**Comment by nguyenj21** [comment]
So with the latest changes, I made sure to address the console.log errors. Those are there basically to error check for the future. I added a couple more console.log checks and also updated the test case to make sure the values are not undefined and that they are returning the hashPW and the genSalt.

**Comment by nguyenj21** [comment]
Since there is 2 approvals I will merge so I can do other test cases and help out front end with their test cases.

**Pull request merged**
