### PR TITLE
Movies Page Additions

### PR DESCRIPTION
**Pull request by AlvaroH2001**
## Description
Simply added more movies to the catalogue to have enough to be able to have 2 separate rows of movies to give the appearance of a substantial amount of choices.
## Testing
These pages are already 100% covered and stayed that way after my changes.
## Possible Errors
None that I've seen, just a comment though, not sure if it's just on my end but, for some reason whenever I clicked on another page from the header at the top it took 2 clicks each time to navigate to other pages. 
## Images
Screenshot 2024-04-23 at 5 37 05 PM

### CODE REVIEW

**Comment by Redblaze74** [comment]
image

Could you go into the test case file for Movies Page under app/components/moviesPage/... and just change the value from 2 to 1, `toHaveLength(1)`, just so it can pass the build without a failed test case? Also, add the `<Title page="Movies"/>` component before the first h1 just so the page has the title with the icon like the Health Page.

**Comment by AlvaroH2001** [comment]
Thank you @Redblaze74 added those fixes and your cool title component to the page and it looks great and actually passes the checks now, appreciate the helpful reviews.

**Review by Redblaze74 — APPROVED** [review]
LGTM, thanks for getting those quick fixes in the test cases so we don't have a failed workflow. Adding more movies for display helps fill out the page more, good job.

**Review by aiharc1 — APPROVED** [review]
Looks fire. Nice work adding in a crucial part to the app. Everything functions as it should

**Review by salazw1 — APPROVED** [review]
Very nice improvements to the movies page, it does seem like there are many options to choose from now! Everything is coming together nicely.

**Comment by AlvaroH2001** [comment]
Going to go ahead and merge this since it has met the approvals.

**Pull request merged**
