### PR TITLE
Test Cases for Food Page and it's components

### LINKED ISSUE #152: Food
Start to populate the order food page with content

### PR DESCRIPTION
**Pull request by AlvaroH2001**
## Description
In this pull request I've added all of the test files and cases to be able to get 100% coverage of the food page and it's relevant components.
## Testing
The main purpose of this PR was to increase test coverage. 
## Possible Errors
A list of any errors that might be present. Things like edge cases, unexpected interactions with components of the project, etc.
## Images
image

## Relevant AI Documentation
ChatGPT played a heavy role in the creation of a lot of these tests, the main purpose of why AI was used to create the tests is due to time sack and to decrease repetition on this task that would otherwise most likely take me a similar amount of time as it did to create the components themselves. Efficiency was the motivating factor, and the results were very effective in increasing our test coverage.

### CODE REVIEW

**Review by aiharc1 — APPROVED** [review]
Nice work on the test cases Alvaro. Changes look good.

**Review by 39otsu — APPROVED** [review]
L O O K S G O O D T O M E
O
O
K
S
G
O
O
D
T
O
M
E

**Review by Redblaze74 — APPROVED** [review]
LGTM, good work boosting the test coverage up.

**Review by nguyenj21 — APPROVED** [review]
Good job on the test cases, that is very helpful to know that ChatGPT helped you with the test cases, I shall be using that in my test cases as well thank you. Also, maybe you could specify which files specifically you did in the description just in case for the TAs?

**Review by salazw1 — APPROVED** [review]
Good work on adding test cases for the food page which overall improves our test coverage! It's good that you mentioned AI generation usage, thanks for being transparent.

**Comment by aiharc1** [comment]
I will be merging this PR now. There are 5 PR reviews. Thank you

**Pull request merged**
