### PR TITLE
Updating chat page index and chatbox component.

### PR DESCRIPTION
**Pull request by jusasin**
### DESCRIPTION
Simple merge that will update the chatroom to the current so that it is in main. The changes are very simple. The user can no longer send a message before picking who to send a message to. 
image
image
Also noticed that you need to click on the friendslist on the left to populate a variable. Otherwise if you just click on the online users and tried to type you get an error. These fixes could be changed but with the short amount of time and stuff we have to do for the project we are choosing to not handle the errors at this time.

### CODE REVIEW

**Review by tbg510 — APPROVED** [review]
Changes look great, it doesn't make sense to send a message before selecting the recipient.

**Review by salazw1 — APPROVED** [review]
Nice change to the logic of chat messaging.

**Review by junxjr — APPROVED** [review]
The chat page looks good! Great work.

**Review by aiharc1 — APPROVED** [review]
Looks good Justin. Nice work on the chat

**Pull request merged**
