### PR TITLE
Worked on Settings Page, Light/Dark Mode, Avatar Customization

### PR DESCRIPTION
**Pull request by Redblaze74**
## Issues
#217 [Light/Dark], #218 [Settings], #219 [Profile Customization]

## Description
- Filled out the settings page with planned display and some foundational functionality
- New components: settingsProfile and settingsTheme
  - settingsProfile: handles customization of user profile by having a preview on the left side and selections of avatars and background on the right. Currently, cancel will reset it to default values and save has no functionality as of now.
  - settingsTheme: handles changing the webpage to either light/dark mode after user saves their preference
- Modifications to data.js and header component to include further page data that may not be wanted to display in the header tabs
- Modification to profile and profileIcon component to have passed size values for reusability throughout site
- Minor Modification to app ProfileDropdown.js and test case to fix settings redirect 
- Added more icons and attributions for use in Settings page
- Modifications to test cases in order to prevent failed tests

## Testing
There are currently no tests for the added functionality.

## Possible Errors
There is no implementation that acts as a failsafe incase the ID is out of the range of existing ones. While I don't believe users will be able to access it easily, it's something to look out for in the future. Potential issue in responsiveness as that was not in mind during development but was content was contained within the allowed range of the div from the layout component.

## Images
image
image
image
image

### CODE REVIEW

**Review by tbg510 — APPROVED** [review]
Looks amazing, nice work! The settings page has a lot of great new content that our users will appreciate.

**Review by salazw1 — APPROVED** [review]
Nice work in updating the settings page, it looks exciting and engaging from a user standpoint! I'm sure users will be happy in customizing their profiles now!

**Review by AlvaroH2001 — APPROVED** [review]
Absolutely wonderful job on these changes I love what you did with the place, the settings page looks so much more lively now and I really like the customization aspect for the avatar, really cool.

**Comment by AlvaroH2001** [comment]
Thank you for adding the movies to the new layout, going to go ahead and merge this since it has all the approvals and I want to start work on the home page as quick as I can.

**Pull request merged**
