### PR TITLE
Added SidebarButton defining dynamic HoverButton based on given props and adjusted SideBar to map out a list of buttons that send props to dynamic sidebarButtons

### PR DESCRIPTION
**Pull request by blake-gilmore**
This closes issue #52 

Creates a SidebarButton reusable component for... sidebar buttons. Returns a HoverButton component with the given props.

Rewrites Sidebar.js component to map a list of button json objects to various sidebar buttons.

### CODE REVIEW

**Comment by blake-gilmore** [comment]
The links don't work!

**Review by salazw1 — APPROVED** [review]
All of the sidebar buttons still redirect to the correct page, and they do make a hover motion whenever the cursor is over it. Very clever to implement a SidebarButton/HoverButton, it is very possible we may need to utilize these components again; it could prove to be useful for other applications. Great work!

**Review by Redblaze74 — APPROVED** [review]
Looks good to me

**Review by AlvaroH2001 — APPROVED** [review]
Everything looks good and works well on my end, appreciate the optimization.

**Comment by AlvaroH2001** [comment]
Closes #52

**Pull request merged**
