### PR TITLE
Implement MongoDB Integration and Login Page Mockup

### PR DESCRIPTION
**Pull request by 39otsu**
These changes provide us with a working example of how frontend and backend operations work, and aim to improve the project's functionality by integrating MongoDB for database operations and providing a mockup for testing user authentication. 

1. **Added MongoDB Integration**
   - Added MongoDB to dependencies to facilitate database operations.
   - Implemented a handler class for managing MongoDB connections, document insertions, and retrievals.

2. **Created Login Page Mockup**
   - Developed a mockup of the login page to facilitate testing of database connections and user login functionality.
   - Included a demonstrative `handleSubmit` server action for testing purposes.

## Additional Suggestions:
- **Improvements to MongoDB Handler Class**: Consider adding error handling mechanisms, connection pooling, and logging functionality to enhance the robustness and reliability of the MongoDB handler class.
- **Enhancements to Login Page Mockup**: Add form validation logic, implement client-side and server-side authentication, and enhance the UI/UX of the login page for better user experience.
- **Documentation**: Provide documentation for the MongoDB handler class, including usage examples, API documentation, and configuration options. Additionally, document the login page mockup, including its purpose, usage instructions, and potential future enhancements.
- **Unit and Integration Tests**: Write unit tests to ensure the correctness of the MongoDB handler class and integration tests to validate the functionality of the login page mockup. Test cases should cover different scenarios, including success and failure cases.

By incorporating these suggestions, we can further improve the quality and effectiveness of the implemented features and ensure the project meets the requirements and expectations.

### CODE REVIEW

**Review by blake-gilmore — APPROVED** [review]

**Review by salazw1 — APPROVED** [review]
great baseline

**Comment by jusasin** [comment]
It is a great start and the additional suggestions help with what else to work on, thank you for including those

**Comment by junxjr** [comment]
great changes and suggestions.

**Review by junxjr — COMMENTED** [review]
looks good

**Pull request merged**
