### PR TITLE
Added test cases for HealthPage 

### PR DESCRIPTION
**Pull request by nguyenj21**
### Issue Number

Resolves https://github.com/UNLV-CS472-672/2024-S-GROUP4-SMTK/issues/197

### Description
Wrote test cases for health page. 

### Testing

100% test coverage
image

### Possible Errors

No possible errors known

### CODE REVIEW

**Review by junxjr — APPROVED** [review]
That's a lot of test cases! Great job on getting them done, this should add a huge amount to our global coverage.

**Review by 39otsu — APPROVED** [review]
SHIP IT

**Review by Redblaze74 — APPROVED** [review]
LGTM, good work documenting where AI generated code was used and thank you for working on getting the test coverage up.

**Review by aiharc1 — APPROVED** [review]
Very nice on the test cases Johnson. I good work with the test coverage again

**Review by salazw1 — APPROVED** [review]
Good job adding more test coverage!

**Comment by aiharc1** [comment]
We have 5 PR accpetanced. Merging

**Pull request merged**
