### PR TITLE
Revised condition for COPPA message & added more test cases

### PR DESCRIPTION
**Pull request by salazw1**
## Issue Number
Adds to #192, #58
## Description

- COPPA message now shows regardless of age when successfully creating an account
- Revised test cases for accountCreate
- Created test cases for some Friends components 
- Created test cases for missing DB files

## Testing
Test cases have been added/revised for files from previous pull requests.

image

Current test coverage:
image

### CODE REVIEW

**Review by Redblaze74 — APPROVED** [review]
LGTM, thanks for staying on top of test coverage especially since we are nearing the deadline. A minor thing I'd want to change here is instead of using window.location.href we use <Link href="/login"/> instead, but it is unimportant in what we are currently trying to accomplish.

**Review by aiharc1 — APPROVED** [review]
Nice work getting that updated and for working on the test coverage. I think we should be nearing 90 very very soon!

**Review by tbg510 — APPROVED** [review]
More test cases more happiness. I want to see more test cases!!

**Review by AlvaroH2001 — APPROVED** [review]
Great job on the updates and additional test files, it's an honest day's work and very much appreciated.

**Pull request merged**
