### PR TITLE
Code used to Produce Charts for DP II/III

### PR DESCRIPTION
**Pull request by jusasin**
Code required to produce the different charts needed for Design Portfolio II and III. This is for team contribution charts, will also need those who review to check that you have registered your name in your individual GitHub Accounts. The code is from his repo that he linked us in Design Portfolio I

### CODE REVIEW

**Review by salazw1 — APPROVED** [review]
good start on implementing the contribution charts

**Review by junxjr — APPROVED** [review]
This looks good for making the charts for team report.

**Review by 39otsu — APPROVED** [review]
LOOKS GOOD TO ME

**Review by blake-gilmore — APPROVED** [review]
Very nicee

**Pull request merged**
