### PR TITLE
Partial Credential Checking (Conditional Redirection) & new button

### PR DESCRIPTION
**Pull request by salazw1**
collaborated with @aiharc1 and @nguyenj21 

- Checked and added function to determine if username and password fields are blank before redirecting to homepage (incorrect credentials still leads to redirect)

- Added new button for admin account creation (no functionality yet)

Additionally renamed the /test directory to /login (more appropriate)

### CODE REVIEW

**Review by aiharc1 — APPROVED** [review]
Worked in partnership with security team @salazw1 @nguyenj21.

Changes look good. Runs as it should. We are still continuing to work on the admin creation page as the team discussed.

**Review by nguyenj21 — APPROVED** [review]
partial credential checking working, need to add an admin page with the same thing

**Review by junxjr — APPROVED** [review]
Looks good for register account and check password.

**Comment by aiharc1** [comment]
Security Team Progress Report
Name: Cade Aihara, Johnson Nguyen, Warren Salazar (Warren handled the github commit)
Time Started: 11 AM
Time Ended: 2:30PM
Issue #13 Account Credential
Issue #34 Admin Account Creation
Issue #9 Create Modules for login page

Login Page:
Added partial credential checking -  determine if either username or password field are blank, if not don't proceed with redirect (still working on mongodb utilization)
Added new button for admins creating new accounts for patients (wip)

Admin Creation Page
Created New Page
Takes basic info (first, last, DOB, Username, Password)
Checks to see if Username/PW contains the First or Last name of patient
Checks to see if all fields are filled in
Does not submit to mongodb yet
Upon submission it will redirect to the login page and give a success message

**Pull request merged**
