### PR TITLE
Added Test Cases to Components and Pages

### PR DESCRIPTION
**Pull request by Redblaze74**
**Issue Number**
Test Cases for PR #176 which dealt with issue #141 [Migration]

**Description**
- Created test cases for the new migrated pages under __tests__ folder
- Created test case for new app component ProfileDropdown.js
- Revised previous test cases for app components TopBar, SideBar, and ThemeLayout
- Minor modification to components Layout, Header, Footer, and Logo with `import React from 'react';` to pass testing for pages
- Minor modifications in changing redirects from _./movie_ to _./movies_ and _./game_ to _./games_
- Commented where AI provided code was in test files
  - Informed that __tests__ folder must be created to pass build tests
  - Needed const Mocks in ThemeLayout and TopBar in order to pass lint tests
  - Provided solution to handling tests in SideBar for different WindowWidths (Desktop/Mobile) testing
  - Provided reusable and simple solution to creating data-testid in ProfileDropdown.js for use in testing
 
**Testing**
100% Coverage in:
- pages: events, friends, games, health, movies, profile, settings
- components: ProfileDropdown, SB_ExpandButton, SideBar, ThemeLayout, TopBar

**Possible Errors**
Most likely something going on with my local machine as testing workflow passed successfully on here but something I should leave here just in case.
image
image
image

**Images**
image
image

### CODE REVIEW

**Review by 39otsu — APPROVED** [review]
If errors exist but you are getting 100% test coverage, then no errors exist. :)

**Review by tbg510 — APPROVED** [review]
Great work on adding more tests. Important that we keep the percentage up.

**Review by aiharc1 — APPROVED** [review]
Nice work on the test coverage Alec. Looks good to me and everything works well as far as I can see.

**Review by salazw1 — APPROVED** [review]
Good job on adding more to our overall test coverage! Much appreciated!

**Comment by aiharc1** [comment]
There are 4 PR reviews. I will be merging now. Thank you everyone

**Pull request merged**
