### PR TITLE
added all the test from everyone

### PR DESCRIPTION
**Pull request by junxjr**
### Title
Added all the test from everyone

### Description
Added all the tests from everybody

### Possible Errors
I don't see any errors right now, but if you run into something, please let me know.

### Image
image

### CODE REVIEW

**Review by tbg510 — APPROVED** [review]
Nice, great tests. Love the test coverage number going up! Wooooo!

**Comment by aiharc1** [comment]
Nice test coverage. Coming down to the wire here. May need to accept despite one failure

**Review by nguyenj21 — APPROVED** [review]
good job test coverage, make sure to fix the package json

**Review by aiharc1 — APPROVED** [review]
LETS GOOO nice job. Finishing up around here. Everything Looks GOOOD

**Review by jusasin — APPROVED** [review]
Everything looks fantastic! We did our best for the test coverage but we got it to a good point! We were so close but so short on time its all good!

**Review by salazw1 — APPROVED** [review]
Great job everyone for your contributions to one of our last pull requests!

**Pull request merged**
