### PR TITLE
Health Page

### LINKED ISSUE #148: Health Page
Start to populate the health page with content

### PR DESCRIPTION
**Pull request by AlvaroH2001**
## Description
This pull request adds content to the health page, there are now 3 main components in the health page. The `MedicationSchedule` component, the `HealthcareTeam` component, and the `PatientReport` component. 
`MedicationSchedule`: This lists the hypothetical medications that the patient should be taking and also has a toggle feature for them to mark it as 'taken' or 'not taken'. 
`HealthcareTeam`: Shows off a few members of the healthcare team that the patient can contact and if they're 'available' or not. 
`PatientReport`: Is essentially a daily questionnaire for the patient to report their general well being to their team. A submit button is at the bottom that when clicked submits the results (deletes them).
## Testing
Going to go ahead and leave the testing on this PR to Johnson,  here are the components that need testing:
Screenshot 2024-04-21 at 6 09 20 PM

## Possible Errors
Hopefully there shouldn't be any errors with these files specifically. Oddly enough during this development process I did come across a rather annoying issue of the pages reloading themselves infinitely when something small was changed such as a text color or comment. Which really made no sense and I could not figure out what the common cause or trigger was, something to keep an eye out for.

## Images
Screenshot 2024-04-21 at 6 11 38 PM

Screenshot 2024-04-21 at 6 11 55 PM
Screenshot 2024-04-21 at 6 12 04 PM
Screenshot 2024-04-21 at 6 12 07 PM

### CODE REVIEW

**Review by junxjr — COMMENTED** [review]
The health page looks really nice by adding medication, patient report, and health care items. It looks like all the tests for other page like games, movies, etc are failing for some reason, maybe if you can take a look at that since all the pages moved to different folders.

**Comment by AlvaroH2001** [comment]
Shoutout to @Redblaze74 for figuring out why I caused all the tests to fail, everything works now for past and future reviewers.

**Review by junxjr — APPROVED** [review]
Everything looks good. Great job!

**Review by salazw1 — APPROVED** [review]
The health page looks GREAT! Everything is very organized and seems easy to use. Also, nice job on fixing the tests issue.

**Review by aiharc1 — APPROVED** [review]
Seriously nice work here. Very impressed by the functionality and the looks of this page. Took it from 0 to 100 real quick.

**Comment by aiharc1** [comment]
Actually one small thing. I noticed that when clicking the hamburger menu "home" when inside another page like health, chat, etc, it will take you to the login page and not the homepage. Just a small thing but we can fix that in another PR if necessary

**Review by jusasin — APPROVED** [review]
Besides the small issue that cade mentioned earlier, everything looks great! The information on the health page is really nice and very needed content. Great job!

**Pull request merged**
