### PR TITLE
Created test case for SidebarButton component

### PR DESCRIPTION
**Pull request by tbg510**
## Issue Number
#58 Expand test coverage to 90%
## Description
Includes 3 tests for the SidebarButton component, currently only 2/3 tests work. 
- Test 1 checks to see if the SidebarButton renders the correct image when not hovered.
- Test 2 checks to see if the SidebarButton renders the correct image when hovered.
- Test 3 checks to see if the SidebarButton redirects to the correct page when clicked.

Test 1 and 2 are successful, while Test 3 is not. I've tried several methods to make it work, even referencing the page redirect check from the TopBar test, but this test still fails. The successful tests do count as 100% coverage for the SidebarButton component, however, so I decided to still add this test case. Test 3 is still included in the test file commented out if anyone wants to take a look. 

## Testing
According to jest, this test has 100% coverage for the SidebarButton component. Obviously there's more to test but that'll have to wait for the future.
## Possible Errors
Test 3 doesn't work properly so something is wrong there. Otherwise I think these tests are enough to test the SidebarButton component. This could be proven wrong in the future, whether through an oversight in testing or an edit of the component.
## Images
image
image
Current test coverage as of this pull request.
image
Individual test cases passing.

### CODE REVIEW

**Review by junxjr — APPROVED** [review]
I ran the test case files, and the percentage came out to be 100% for all of the them. Although I am not sure how to actually implement the test 3 when page direct successfully, but I do think it is important to test it. That can be handled for the next sprint if anyone knows how to write test cases for it. Great work on making the test cases.

**Review by nguyenj21 — APPROVED** [review]
Approved for the 2 test cases, I think you should edit your PR and add in the screenshots of the test passing to be more specific for the professor.

**Comment by tbg510** [comment]
> Approved for the 2 test cases, I think you should edit your PR and add in the screenshots of the test passing to be more specific for the professor.

Done, thanks for the suggestion.

**Review by salazw1 — APPROVED** [review]
Good work on adding to our overall test coverage! This addition is very well documented and helpful in knowing what should be expected regarding the SidebarButton. I am not sure how to assist in test 3, but I hope that test can work in the future.

**Review by jusasin — APPROVED** [review]
Very good note to mention that a functionality was failing to be tested. We can look further into the test. I tried several ways as well and found that you ran into the same issues by discussing it with you. We can come together later to further develop this test, but we know that the functionality works since actually working on the website we are actually redirected properly. It is interesting that jest still covers a full 100% of lines though. Good work none the less.

**Pull request merged**
