### PR TITLE
Add issue template - delete some unnecessary files

### LINKED ISSUE #119: Add issue template
### Description
In addition to our existing PR template, we need to add one for all past and future issues.

### Possible Solution
In addition to creating a markdown file for the new template, we should also organize both templates into a template directory under our docs directory

### PR DESCRIPTION
**Pull request by blake-gilmore**
## Description
This PR deletes a few unnecessary files in root. (Those pesky package and node modules keep making their way into the root folder somehow), as well as moving our existing PR template to a templates directory. I've also created a simple issue template that can be used for any type of issue. This template likely contains a number of unnecessary subheaders, so if they don't make sense for your specific issue, feel free to exclude them.

### CODE REVIEW

**Review by junxjr — APPROVED** [review]
Thank you for making the issue template!

**Comment by nguyenj21** [comment]
Thank you for organizing this, it helps clean up all the mess which makes the directory cleaner to work in.

**Review by nguyenj21 — APPROVED** [review]
Thank you for organizing this, it helps clean up all the mess which makes the directory cleaner to work in.

**Review by tbg510 — APPROVED** [review]
The issue template looks good; the sections included make sense and will be useful for future issues (if applicable). Also feels nice to organize the project more, so creating a templates folder and removing unnecessary files/folders is good to see. Thanks for doing so!

**Pull request merged**
