### PR TITLE
wrote test cases for moviesPage

### PR DESCRIPTION
**Pull request by nguyenj21**
### Issue Number

Resolves https://github.com/UNLV-CS472-672/2024-S-GROUP4-SMTK/issues/200

### Description
Wrote test cases for movies page. 

### Testing

100% test coverage

image

### Possible Errors

No possible errors known

### AI Documentation/Usage
Used CHATGPT to help with the test cases, documented in the code.

### CODE REVIEW

**Comment by nguyenj21** [comment]
image
My tests are passing, it is just Cade's test that is failing that he is fixing.

**Review by junxjr — APPROVED** [review]
Tests looks great! The workflow fails since the account creation page pr for the privacy agreement, but it was from the other PR. So once they fixed theirs, it should be good to merge.

**Review by tbg510 — APPROVED** [review]
Love me some more test cases!! I want to see even more!!

**Review by salazw1 — APPROVED** [review]
Nice job on adding test coverage for the Movies files! Keep up the great work!

**Review by AlvaroH2001 — APPROVED** [review]
Great job on such a quick output on the movies page, very useful and very relieving that I didn't have to worry about this, thank you.

**Review by aiharc1 — APPROVED** [review]
Nice work improving the test coverage for the movies. Nice work keep it up

**Review by jusasin — APPROVED** [review]
Great additional test cases to the movie page! This helps increase our total to more than 90 percent!!

**Pull request merged**
