### PR TITLE
Names for the chatroom based on login

### PR DESCRIPTION
**Pull request by jusasin**
### Issue numbers
Work towards completing #199, need to complete separate chat boxes.
### Description 
The proper name now shows for the user as long as there is a proper session_id for the user in the cookie. If there is not a proper session_id the user will not be able to join the chatroom.
### Testing
Will work on testing for all chat related pages once I get to a point that is good.
### Possible Errors
No proper session_id will lead to kicking you back into the login page. 
## Pictures 
When running the socket server and the local host you will be able to see that with a proper session_id for the user, the name will appear in the chat room.
image

### Contributors 
39otsu
### AI Usage
No AI usage was utilized during this pull request or creation of code.

### CODE REVIEW

**Review by Redblaze74 — APPROVED** [review]
LGTM, don't know much about the backend work going into the chatroom but I think its great that you started adding usernames into the chatroom so people can identify individual users that are in the chatroom.

**Review by aiharc1 — APPROVED** [review]
Nice work Justin this is HUGE. We finally can say we know who we are texting when we send messages. Nice touch adding in the banner too. Good job

**Review by nguyenj21 — APPROVED** [review]
Good job on fixing the deployment issues. Session id shouldnt be a big deal so approved.

**Review by junxjr — APPROVED** [review]
Great job on getting the users! Do I need to run the chatroom locally? When I open the vercel deployment, and chat page just direct me to the login page.

**Review by salazw1 — APPROVED** [review]
Good work on showing the current user in the chatroom. I couldn't figure it out on my own so kudos to you!

**Review by 39otsu — APPROVED** [review]
LGTM

**Pull request merged**
