### PR TITLE
Ensured COPPA compliance & created simple privacy policy - collaborated w/ @aiharc1

### LINKED ISSUE #192: Make sure to adhere to COPPA
Because we are advertising this app for children, we need to make sure that we follow the guidelines for COPPA.

### PR DESCRIPTION
**Pull request by salazw1**
## Issue Number
Resolves #192 
## Description
Made sure to adhere to the guidelines of COPPA.
- Displayed COPPA message when creating an account.
- Created checkbox (required) for users to accept the T&C/Privacy Policy
- Created Privacy Policy button on footer, redirects to privacy policy page
- Privacy Policy page displays our privacy policy

## Testing
Test cases need to be added for the added files; coverage for these files will be added later.

## Possible Errors
No possible errors known, however scrollbars now show 

image
image

### CODE REVIEW

**Comment by aiharc1** [comment]
Nice team work parthah. We will do the test cases now

**Review by nguyenj21 — APPROVED** [review]
Seems like 3 tests are failing because of not enough test coverage, I think Alec's change made the footer.test.js stop working as well? We can fix it after though no worries approved.

**Review by tbg510 — APPROVED** [review]
Great job including considerations for COPPA. It's nice to have something tangible to show that we have this in mind. Hopefully the tests can be fixed soon.

**Review by jusasin — APPROVED** [review]
LGTM, we really needed to add this policy it is very important to show this implementation so that we can work talk head on about the legal problems we were thinking about. GREAT WORK!

**Review by Redblaze74 — APPROVED** [review]
LGTM, just need the test cases done and it should be good.

**Review by 39otsu — APPROVED** [review]
This is a good pull request that really sets us apart from competitors. Great job!

**Comment by aiharc1** [comment]
We have 4 approvals. going to merge
thank you

**Pull request merged**
