### PR TITLE
Updated README with testing information and adjusted npm run test script

### LINKED ISSUE #67: Add some testing information in our README with specific instructions and info
Should also add some testing information in our README in the future for more specific step-by-step instructions as well as our requirements for 90% or any other testing-specific info we'd want to add.

_Originally posted by @blake-gilmore in https://github.com/UNLV-CS472-672/2024-S-GROUP4-SMTK/issues/66#issuecomment-1987416201_

### PR DESCRIPTION
**Pull request by blake-gilmore**
### Description
The README now includes a section about Jest as our testing suite and a short list of instructions on how to test. This also explains the three main testing scripts our app has available through 'npm run'. These are:
- npm run test
- npm run test:watch
- npm run test:coverage

### Testing
No test cases were added here.

### Possible Errors
No errors, but there could be more information included here so feel free to suggest and I can update this

### CODE REVIEW

**Review by jusasin — APPROVED** [review]
Good work adding the testing information to the readme. Makes it a lot easier to figure out how to run and fix tests. Good idea to recognize that coverage needs to be at least 90%, so when things are added, they include tests that covers those new additions.

**Review by Redblaze74 — APPROVED** [review]
Looks good to me, thanks for adding information on how we can perform testing in a clear manner and making it easier to access rather than having to reiterate the question or having to look back at prior messages.

**Review by aiharc1 — APPROVED** [review]
Looks good.  Thank you for adding further instruction on the README. It makes it clearer on what actions need to be completed prior to using this app.

**Review by AlvaroH2001 — COMMENTED** [review]
Documentation is well-structured and informative, providing a solid foundation for project contributors to understand and engage with the testing process.

**Pull request merged**
